services:
  db:
    image: postgres:15
    restart: always
    container_name: piscineds-db 
    environment:
      POSTGRES_USER: erivero-p
      POSTGRES_DB: piscineds
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
      # those environment variables will config the server on pgAdmin:
      # PGADMIN_CONFIG_SERVER_MODE: "True"
      # PGADMIN_CONFIG_DEFAULT_SERVER: "PiscineDB"
      # PGADMIN_CONFIG_DEFAULT_SERVER_HOST: "db"
      # PGADMIN_CONFIG_DEFAULT_SERVER_PORT: "5432"
      # PGADMIN_CONFIG_DEFAULT_SERVER_USER: "erivero-p"
      # PGADMIN_CONFIG_DEFAULT_SERVER_PASSWORD: "mysecretpassword"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./vol-pgadmin:/var/lib/pgadmin

volumes:
  pgdata:

