services:
  db:
    image: postgres:15
    restart: always
    container_name: piscineds-db 
    environment:
      POSTGRES_USER: erivero-p
      POSTGRES_DB: piscineds
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./csv_data:/csv_data
      - ./scripts:/scripts
    networks:
      - piscineds-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpassword"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - piscineds-network

volumes:
  pgdata:

networks:
  piscineds-network:
    driver: bridge
